# Welcome to Jekyll!

# Website settings
title: Portfolio of Ryan Moser
description: Ryan's Portolio
keywords: blog,Jekyll,github,gh-pages,resume,ryan,moser,portfolio,unity,
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://ryemoss.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Ryan Moser  # Be used at blog posts' author.
  first_name: Ryan  # Be used at index page about me section.
  last_name: Moser  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: ryemoss  # Leave blank if you don't have now
  linkedin_id: ryanfmoser # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: rmosyr@gmail.com  # Leave blank if you don't have now
  cv:  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-csharp
    - name: fa-android
  skill_icon2:
    - name: icon-3dprint
    - name: icon-javascript
  desc: Engineer, designer, coder.  # Describe yourself.

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

donation: off

## carousels
index_carousel: on
blog_carousel: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
